In [45]:
# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

# solution creating the 3 x 3 matrix with number number
import numpy as np

random_num = np.random.randint(1,101, size= (3,3))

print('Before matrix: \n',random_num)
transpose = random_num.transpose()

print("After exchanging rows and columns :\n",transpose)

Before matrix: 
 [[ 3 55  4]
 [99 34 31]
 [72 50 48]]
After exchanging rows and columns :
 [[ 3 99 72]
 [55 34 50]
 [ 4 31 48]]


In [48]:
# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.


array_1d = np.arange(1,11)
print("1d array: \n",array_1d)
size_2x5 = array_1d.reshape(2,5)
print("2d array size 2x5: \n",size_2x5)

size_5x2 = array_1d.reshape(5,2)
print("2d array 5x2: \n",size_5x2)


1d array: 
 [ 1  2  3  4  5  6  7  8  9 10]
2d array size 2x5: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2d array 5x2: 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [79]:
# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.


array_4x4 = np.random.rand(4, 4)


array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

array_4x4, array_with_border


(array([[0.19045271, 0.17434036, 0.14895921, 0.65584623],
        [0.40245093, 0.39232708, 0.47384367, 0.95542708],
        [0.29095918, 0.99793065, 0.3831748 , 0.61496764],
        [0.45057208, 0.33340232, 0.87145473, 0.07723476]]),
 array([[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.19045271, 0.17434036, 0.14895921, 0.65584623,
         0.        ],
        [0.        , 0.40245093, 0.39232708, 0.47384367, 0.95542708,
         0.        ],
        [0.        , 0.29095918, 0.99793065, 0.3831748 , 0.61496764,
         0.        ],
        [0.        , 0.45057208, 0.33340232, 0.87145473, 0.07723476,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ]]))

In [80]:
# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.


array_step = np.arange(10, 65, 5)
array_step


array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [81]:
# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
# (uppercase, lowercase, title case, etc.) to each element.

# Create a NumPy array of strings
array_strings = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
upper_case = np.char.upper(array_strings)
lower_case = np.char.lower(array_strings)
title_case = np.char.title(array_strings)
capitalize_case = np.char.capitalize(array_strings)

upper_case, lower_case, title_case, capitalize_case


(array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6'),
 array(['python', 'numpy', 'pandas'], dtype='<U6'),
 array(['Python', 'Numpy', 'Pandas'], dtype='<U6'),
 array(['Python', 'Numpy', 'Pandas'], dtype='<U6'))

In [ ]:
# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

# Create a NumPy array of words
words_array = np.array(['hello', 'world', 'numpy', 'array'])

# Insert a space between each character of every word in the array
spaced_words_array = np.char.join(' ', words_array)

spaced_words_array


In [96]:
# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
array_1 = np.array([[1,2,3,4],[5,6,7,8]])
array_2 = np.array([[10,12,13,14],[16,17,18,19]])

multi = np.multiply(array_1,array_2)
addition = np.add(array_1,array_2)
subtraction = np.subtract(array_1,array_2)
division = np.divide(array_1,array_2)

print("multiplication: \n",multi,"\n")
print("Addition: \n",addition,"\n")
print('Subtraction: \n',subtraction,"\n")
print('Diviion: \n',division,"\n")

multiplication: 
 [[ 10  24  39  56]
 [ 80 102 126 152]] 

Addition: 
 [[11 14 16 18]
 [21 23 25 27]] 

Subtraction: 
 [[ -9 -10 -10 -10]
 [-11 -11 -11 -11]] 

Diviion: 
 [[0.1        0.16666667 0.23076923 0.28571429]
 [0.3125     0.35294118 0.38888889 0.42105263]] 



In [97]:

# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements

identity_matrix = np.eye(5)

diagonal_elements = np.diag(identity_matrix)

print("Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)


Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


In [98]:
# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
# this array.



def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True


random_integers = np.random.randint(0, 1001, size=100)

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

print("Random Integers:", random_integers)
print("Prime Numbers:", prime_numbers)


Random Integers: [347 574 186 932 438 241  61 222 908 248 743 151 631  19 460 784 109 905
 737 639 313  14 839 741   9 863 984 711 637  95 319 712 913 890 477 268
  19 170 389 766  75 297  25 123 248 143  12 556  21  96 883 928 766 729
  18  76 526  28  51 758 758 924 260 656 120 230 504 464 112 311 886 778
 931 173 303 110 472 967 817 607 810 187 989 789 892 390 544 381 192 219
 708 295 995 559 344 740 955 966 771 400]
Prime Numbers: [np.int32(347), np.int32(241), np.int32(61), np.int32(743), np.int32(151), np.int32(631), np.int32(19), np.int32(109), np.int32(313), np.int32(839), np.int32(863), np.int32(19), np.int32(389), np.int32(883), np.int32(311), np.int32(173), np.int32(967), np.int32(607)]


In [99]:
# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
# averages.abs
import numpy as np


daily_temperatures = np.random.randint(15, 35, size=30)  


weeks = daily_temperatures[:28].reshape(4, 7)
extra_days = daily_temperatures[28:]


weekly_averages = np.mean(weeks, axis=1)


if extra_days.size > 0:
    extra_days_average = np.mean(extra_days)
    weekly_averages = np.append(weekly_averages, extra_days_average)

print("Daily Temperatures:", daily_temperatures)
print("Weekly Averages:", weekly_averages)


Daily Temperatures: [19 23 33 20 30 24 15 34 18 28 17 29 18 34 29 25 27 22 17 25 29 24 15 16
 27 20 20 17 15 15]
Weekly Averages: [23.42857143 25.42857143 24.85714286 19.85714286 15.        ]
