In [ ]:
# 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
# enhance Python's capabilities for numerical operations?

# Purpose of NumPy in Scientific Computing and Data Analysis
# NumPy (Numerical Python) is a powerful Python library primarily used for numerical computing. It is designed to perform efficient operations on large multi-dimensional arrays and matrices, which are crucial in scientific computing and data analysis.

# Key Features of NumPy:
# Multidimensional Arrays (ndarray): NumPy provides the ndarray object, a versatile, n-dimensional array that holds elements of a single data type. This allows handling of complex datasets efficiently.

# Mathematical Functions: NumPy includes a vast collection of mathematical operations, including element-wise functions, linear algebra routines, and statistical operations, making complex calculations easier.

# Efficient Broadcasting: NumPy supports broadcasting, allowing element-wise operations on arrays of different shapes, which reduces the need for explicit loops.

# Integration with Other Libraries: NumPy is the foundation of many scientific libraries in Python, such as SciPy, Pandas, and TensorFlow, making it essential for data analysis and machine learning workflows.

# Advantages of NumPy in Scientific Computing and Data Analysis
# Performance Improvement:

# Vectorization: NumPy allows vectorized operations on arrays, which eliminates the need for explicit loops in Python. This results in faster execution of numerical operations because the computations are done in compiled C code.
# Memory Efficiency: NumPy arrays consume less memory compared to equivalent Python lists due to the compact, continuous memory layout and fixed data types.
# Support for Multidimensional Data:

# NumPy arrays (ndarray) can handle multi-dimensional datasets efficiently, which is essential for handling large datasets in scientific computing.
# It provides a wide range of functionalities for reshaping, slicing, and aggregating arrays, which is important for data manipulation in data analysis.
# Mathematical and Statistical Functions:

# NumPy offers a variety of mathematical, statistical, and linear algebra functions that can be applied directly to arrays, enabling efficient data processing.
# Interoperability with C/C++ and Fortran:

# NumPy arrays can be passed to code written in other languages (C/C++ or Fortran), enabling integration with high-performance libraries while maintaining Python’s ease of use.
# Compatibility with Pandas and Machine Learning Libraries:

# Since libraries like Pandas (for data analysis) and TensorFlow (for machine learning) are built on top of NumPy arrays, it is seamless to switch between them, ensuring smooth transitions between data preprocessing, statistical analysis, and machine learning workflows.
# Enhancing Python’s Capabilities for Numerical Operations
# Fast Array Processing:

# Python’s native lists are slow for numerical computations due to their dynamic nature. NumPy’s arrays, on the other hand, are optimized for fixed-type, homogeneous data, making numerical operations significantly faster.
# Matrix and Linear Algebra Operations:

# Python lacks built-in support for matrix operations and linear algebra. NumPy fills this gap with a rich set of tools for matrix manipulation, inversion, and solving linear equations.
# Efficient Aggregation Functions:

# Functions like sum(), mean(), and min() are optimized in NumPy for arrays, providing faster computation times compared to native Python functions on lists.
# Better Precision Handling:

# NumPy allows the creation of arrays with a variety of numerical data types, including complex numbers and high-precision floating-point numbers, which enhances Python’s ability to handle precision-sensitive calculations.

In [7]:
# 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
# other?

# In NumPy, both np.mean() and np.average() are used to compute the average of an array of numbers, but they have some key differences in functionality and usage. Here's a detailed comparison:

# 1. Basic Functionality
# np.mean():

# This function calculates the arithmetic mean (average) of an array along a specified axis.
# It doesn't take into account any weights; each element is treated equally.
# Example:


import numpy as np
arr = np.array([1, 2, 3, 4])
print(np.mean(arr))  # Output: 2.5
# np.average():

# Similar to np.mean(), it calculates the average of the array, but with an additional feature: you can specify weights.
# By providing a weights parameter, you can compute a weighted average.
# Example:


arr = np.array([1, 2, 3, 4])
weights = np.array([1, 2, 3, 4])
print(np.average(arr, weights=weights))  # Output: 3.0 (weighted average)

# 2. Parameters
# np.mean():

# Array (a): Input array or object that can be converted to an array.
# Axis (axis): Axis along which the mean is computed. If not specified, the mean is computed for the flattened array.
# dtype: The type to use in computing the mean.
# out: Alternative output array in which to place the result.
# np.average():



# 3. Weighted Average Capability
# np.mean():
# Does not support weights, so every element contributes equally to the mean.
# np.average():
# Supports weights, allowing you to assign importance to certain elements, which makes it ideal for computing weighted averages.
# Example of weighted average:


arr = np.array([1, 2, 3, 4])
weights = np.array([1, 0, 0, 0])  # Only the first element is weighted
print(np.average(arr, weights=weights))  # Output: 1.0 (as only 1 is 

# 4. Return Value
# np.mean():


# np.average():
# By default, it returns the weighted average. If you set returned=True, it will return a tuple: the weighted average and the sum of the weights.
# 5. When to Use Which Function?
# Use np.mean():

# When you want a simple arithmetic mean, and you don’t need to consider weights.
# It's more straightforward and slightly faster for unweighted averages.
# Example: Calculating the average of a data set where each element has equal importance:


arr = np.array([1, 2, 3, 4, 5])
result = np.mean(arr)  # Arithmetic mean
# Use np.average():

# When you need to compute a weighted average and the contribution of each element varies.
# It's the go-to function when weights are involved in the calculation.
# Example: Computing the average grade of a student where each exam has a different weight:


grades = np.array([80, 90, 70])
weights = np.array([0.5, 0.3, 0.2])  # Exam 1 is 50% of the grade, Exam 2 is 30%, and Exam 3 is 20%
result = np.average(grades, weights=weights)

2.5
3.0
1.0


In [12]:
# 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
# arrays.

# In NumPy, you can reverse arrays along different axes using various techniques. These methods allow you to reverse the elements of 1D, 2D, or multi-dimensional arrays. Below are some common methods for reversing arrays, along with examples for 1D and 2D arrays.

# 1. Using Slicing ([::-1])

# [::-1] reverses the array along its only axis.

# Example (1D array):

import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5])
reversed_arr_1d = arr_1d[::-1]
print(reversed_arr_1d)


# For a 2D array, you can apply slicing to reverse along different axes.

# Reverse rows (axis 0): [::-1, :]
# Reverse columns (axis 1): [:, ::-1]
# Reverse both axes: [::-1, ::-1]
# Example (2D array):

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Reverse rows
reverse_rows = arr_2d[::-1, :]
print(reverse_rows)

# Reverse columns
reverse_columns = arr_2d[:, ::-1]
print(reverse_columns)

# Reverse both rows and columns
reverse_both = arr_2d[::-1, ::-1]
print(reverse_both)

# 2. Using np.flip()
# The np.flip() function allows you to reverse an array along any specified axis or all axes.

# For 1D Arrays:
# You can reverse a 1D array with np.flip() by specifying the axis (or leaving it blank for the default behavior).


reversed_arr_1d = np.flip(arr_1d)
print(reversed_arr_1d)


# [5 4 3 2 1]
# For 2D Arrays:
# In a 2D array, you can reverse along a specific axis:



reverse_rows = np.flip(arr_2d, axis=0)
print(reverse_rows)

# Reverse columns (axis 1)
reverse_columns = np.flip(arr_2d, axis=1)
print(reverse_columns)

# Reverse both axes
reverse_both = np.flip(arr_2d)
print(reverse_both)



# 3. Using np.fliplr() and np.flipud() (for 2D arrays only)
# np.fliplr(): Reverses the array left to right (i.e., reverses the order of columns). Only works for 2D arrays.

# np.flipud(): Reverses the array upside down (i.e., reverses the order of rows). Only works for 2D arrays.


# Flip left to right (reverse columns)
fliplr_arr = np.fliplr(arr_2d)
print(fliplr_arr)

# Flip upside down (reverse rows)
flipud_arr = np.flipud(arr_2d)
print(flipud_arr)


# 4. Using np.transpose() and np.rot90()
# np.transpose(): Transposes the dimensions of the array. For a 2D array, it swaps rows and columns.

# np.rot90(): Rotates the array 90 degrees in a specified direction (counterclockwise by default).

# Example (Transpose and Rotate):

transpose_arr = np.transpose(arr_2d)
print(transpose_arr)

# Rotate array 90 degrees
rot90_arr = np.rot90(arr_2d)
print(rot90_arr)




[5 4 3 2 1]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[5 4 3 2 1]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[3 6 9]
 [2 5 8]
 [1 4 7]]


In [27]:
# 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
# in memory management and performance.

# In NumPy, the data type of elements in an array is an essential attribute because it affects both memory management and performance. Here's how you can determine the data type and why it is important.

# 1. Determining the Data Type of a NumPy Array
# You can determine the data type of elements in a NumPy array using the .dtype attribute.

import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr.dtype)  # Output: int64 (or int32 depending on your system)

arr_float = np.array([1.0, 2.0, 3.0])
print(arr_float.dtype) 

# Other Useful Methods:
# astype(): You can also use the astype() method to convert the data type of an array.

arr_float = arr.astype(np.float64)  # Convert integer array to float64
print(arr_float.dtype)  # Output: float64

# np.can_cast(): You can check if an array can be safely cast from one data type to another using np.can_cast().

print(np.can_cast(arr, np.float32))  # Output: True

# 2. Importance of Data Types in Memory Management and Performance
# The data type (dtype) of a NumPy array controls how the elements are stored in memory and how much space each element takes. The most common data types include integers, floats, complex numbers, and booleans. Each data type requires a different amount of memory, which has a direct impact on the performance of operations on arrays.

arr_int8 = np.array([1, 2, 3, 4], dtype=np.int8)  # 1 byte per element
arr_int64 = np.array([1, 2, 3, 4], dtype=np.int64)  # 8 bytes per element

print(arr_int8.nbytes)  # Output: 4 bytes
print(arr_int64.nbytes)  # Output: 32 bytes

# # Performance
# Faster Computation: Operations on smaller data types (e.g., int8, float32) are generally faster because they require fewer CPU cycles and less memory bandwidth compared to larger data types (e.g., int64, float64). This is especially important in high-performance computing, where the efficiency of operations can have a significant impact on overall processing time.

arr = np.random.randint(0, 100, size=(1000000,), dtype=np.int8)  # Smaller data type
arr_large = np.random.randint(0, 100, size=(1000000,), dtype=np.int64)  # Larger data type

%timeit arr + arr  # Faster for int8
%timeit arr_large + arr_large  # Slower for int64

# Floating Point Precision: For floating-point numbers, different data types provide different levels of precision:

# float32 (single precision) takes 4 bytes and is precise to 7 decimal places.
# float64 (double precision) takes 8 bytes and is precise to 15-16 decimal places.
# If you need high precision for scientific calculations, using float64 or even float128 is advisable, but this comes at the cost of additional memory and slower computations.

arr_float32 = np.array([0.1, 0.2, 0.3], dtype=np.float32)
arr_float64 = np.array([0.1, 0.2, 0.3], dtype=np.float64)

print(arr_float32)  # Output: [0.1 0.2 0.3]
print(arr_float64)  # Output: [0.1 0.2 0.3] but with more precision internally

# Type Compatibility and Overflow
# Type-Specific Operations: Some operations behave differently depending on the data type. For example, integer division in int8 could result in overflow, while the same division with int64 would give accurate results.

arr = np.array([128], dtype=np.int16) 
print(arr * 2)  # Output: -256 (Overflow for int8)

# type Casting: While performing operations between arrays of different data types, NumPy follows type promotion rules, where the result will often be cast to the larger of the data types to prevent loss of information. This can have performance implications.




int64
float64
float64
False
4
32
665 μs ± 77.1 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
4.6 ms ± 315 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
[0.1 0.2 0.3]
[0.1 0.2 0.3]
[256]


In [28]:
# 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

# In NumPy, an ndarray (N-dimensional array) is the fundamental data structure used for handling and performing operations on large datasets. It is highly optimized for numerical and matrix-based computations. Here's an overview of ndarrays and how they differ from standard Python lists.

# Definition of ndarray
# An ndarray is a multidimensional, fixed-size container of items of the same type and size. It stands for N-dimensional array, meaning it can handle arrays with any number of dimensions, such as 1D, 2D, 3D, etc.

import numpy as np

# Create a 1D NumPy array (ndarray)
arr_1d = np.array([1, 2, 3, 4])

# Create a 2D NumPy array (ndarray)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print(arr_1d)
print(arr_2d)

# Homogeneous Data Types: All elements in a NumPy array must have the same data type (dtype). This makes operations faster since the array’s memory layout is predictable and efficient.

arr = np.array([1, 2, 3])
print(arr.dtype)  # Output: int64

# Multidimensional: An ndarray can have any number of dimensions, not just 1D like Python lists. This is useful for handling matrices, tensors, and multidimensional data in scientific computing.

arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d.shape)  # Output: (2, 2, 2)

# Vectorized Operations: Operations on NumPy arrays are vectorized, meaning that you can apply operations over entire arrays without the need for explicit loops. This leads to faster and more readable code.

arr = np.array([1, 2, 3])
print(arr * 2)  # Output: [2 4 6] (element-wise multiplication)

# Broadcasting: NumPy allows operations on arrays of different shapes, adjusting smaller arrays to larger ones in a process called broadcasting. This allows for more flexible arithmetic between arrays of different sizes.

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([10, 20])
print(arr1 + arr2)  # Broadcasting: Output: [[11 22], [13 24]]

# Slicing and Indexing: NumPy arrays support advanced slicing and indexing techniques, allowing you to efficiently access and manipulate data.

arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4])  # Output: [2 3 4] (slicing)

# Supports Mathematical Operations: NumPy provides numerous mathematical functions such as sum(), mean(), dot(), etc., optimized for array operations.

arr = np.array([[1, 2], [3, 4]])
print(np.sum(arr))  # Output: 10

# Shape and Reshaping: You can query or change the shape of an array using the .shape attribute or the .reshape() function.

arr = np.array([1, 2, 3, 4, 5, 6])
arr_reshaped = arr.reshape(2, 3)
print(arr_reshaped)
# Output: 
# [[1 2 3]
#  [4 5 6]]

# NumPy arrays are much faster than Python lists, particularly for large datasets. This is due to efficient memory usage and vectorized operations.

import numpy as np
import time

# Using Python list
lst = list(range(1000000))
start = time.time()
lst = [i * 2 for i in lst]  # List comprehension
print("List time:", time.time() - start)

# Using NumPy array
arr = np.arange(1000000)
start = time.time()
arr = arr * 2  # Vectorized operation
print("NumPy time:", time.time() - start)




[1 2 3 4]
[[1 2 3]
 [4 5 6]]
int64
(2, 2, 2)
[2 4 6]
[[11 22]
 [13 24]]
[2 3 4]
10
[[1 2 3]
 [4 5 6]]
List time: 0.11947512626647949
NumPy time: 0.004998445510864258


In [31]:
# 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations

# NumPy arrays (ndarray) offer significant performance advantages over Python lists, particularly for large-scale numerical operations. These benefits are derived from several factors, including memory efficiency, vectorization, and optimized underlying implementations. Let's break down the key performance improvements:

# 1. Memory Efficiency
# NumPy arrays use a contiguous block of memory to store elements of the same type, which allows them to be more memory-efficient compared to Python lists. Python lists, on the other hand, are arrays of pointers to objects, where each element is an independent Python object. This results in higher memory usage and fragmentation.

import numpy as np
import sys

# Python list
py_list = list(range(1000))
print("Python list size:", sys.getsizeof(py_list))  # Size in bytes

# NumPy array
np_array = np.arange(1000)
print("NumPy array size:", np_array.nbytes)  # Size in bytes

# 2. Vectorized Operations
# NumPy allows for vectorized operations, where arithmetic operations (e.g., addition, multiplication) are applied element-wise without the need for explicit loops. This leads to substantial speed improvements because the operations are performed in highly optimized C or Fortran code behind the scenes, avoiding Python’s inherent loop overhead.

import numpy as np

# NumPy array (vectorized operation)
arr = np.arange(1000000)
arr_result = arr * 2  # Fast, element-wise operation

# 3. Optimized for Numerical Computation
# NumPy is implemented in C, and most of its operations are performed in compiled code, avoiding Python's interpreter overhead. This makes operations like summation, multiplication, and other mathematical functions significantly faster.

import numpy as np
import time

# Python list summation
lst = list(range(1000000))
start = time.time()
sum(lst)
print("List sum time:", time.time() - start)

# NumPy array summation
arr = np.arange(1000000)
start = time.time()
np.sum(arr)
print("NumPy sum time:", time.time() - start)

# 4. Efficient Memory Layout
# NumPy arrays are stored in contiguous memory blocks, allowing for much more efficient CPU cache utilization. Python lists, being arrays of pointers to objects, are not as cache-friendly, causing slower access times.

# Strided Memory Access
# NumPy's efficient memory layout allows for strided memory access, where you can quickly access elements of the array using strides. This is not possible with Python lists, which need more memory hops to access individual elements.

# 5. Broadcasting
# NumPy supports broadcasting, which allows arrays of different shapes to be used in arithmetic operations without needing to manually reshape them. This avoids the overhead of explicit loops or reshaping operations and improves performance.

import numpy as np

# NumPy broadcasting
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr_add = arr + np.array([1, 2, 3])  # Broadcasting across the rows
print(arr_add)


# 6. Precompiled Functions and Libraries
# NumPy provides a suite of precompiled functions such as np.dot(), np.linalg.inv(), and np.fft.fft(). These functions are implemented in highly optimized C or Fortran, making them faster than any Python equivalent.

# For example, matrix multiplication with np.dot() is significantly faster than performing the operation manually using Python lists.


import time

# Large matrix
arr = np.random.rand(1000, 1000)

# Timing NumPy dot product
start = time.time()
np.dot(arr, arr)
print("NumPy dot product time:", time.time() - start)

# 7. In-Place Operations
# NumPy supports in-place operations that modify arrays without creating new objects in memory, reducing memory overhead and improving speed.

arr = np.arange(1000000)

# In-place multiplication (no new array created)
arr *= 2  # Faster, modifies the original array in place

# 8. Advanced Indexing and Slicing
# NumPy provides advanced indexing and slicing techniques that allow for efficient access and manipulation of array elements, unlike Python lists where indexing or slicing often results in copies of data or involves more overhead.

arr = np.arange(1000000).reshape(1000, 1000)

# Efficient slicing
sub_array = arr[100:200, 200:300]

# 9. Built-In Mathematical Functions
# NumPy has many built-in mathematical functions that are optimized for performance, such as np.mean(), np.std(), np.sqrt(), etc. These functions are more efficient than manually implementing them in Python using lists.

# NumPy
arr = np.arange(1000000)
mean_value = np.mean(arr)  # Fast and efficient

# Performance Comparison: NumPy vs Python Lists
# Here’s a simple performance comparison between NumPy arrays and Python lists for an element-wise operation:

import numpy as np
import time

# Python list operation
lst = list(range(1000000))
start = time.time()
lst = [x * 2 for x in lst]
print("Python list operation time:", time.time() - start)

# NumPy array operation
arr = np.arange(1000000)
start = time.time()
arr = arr * 2  # Vectorized operation
print("NumPy operation time:", time.time() - start)



Python list size: 8056
NumPy array size: 8000
List sum time: 0.009018898010253906
NumPy sum time: 0.0010023117065429688
[[2 4 6]
 [5 7 9]]
NumPy dot product time: 0.024111509323120117
Python list operation time: 0.0723104476928711
NumPy operation time: 0.004996776580810547


In [32]:
# 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
# output.

# stack arrays vertically and horizontally, respectively. They are often used to combine arrays of compatible shapes along different axes.

# 1. np.vstack(): Vertical Stack
# The np.vstack() function stacks arrays vertically (row-wise). It combines arrays along axis 0, meaning it adds arrays one on top of another.

import numpy as np

# Create two 2D arrays with the same number of columns
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

# Stack arrays vertically (row-wise)
vstack_result = np.vstack((arr1, arr2))
print(vstack_result)

# 2. np.hstack(): Horizontal Stack
# The np.hstack() function stacks arrays horizontally (column-wise). It combines arrays along axis 1, meaning it adds arrays side by side.

# Create two 2D arrays with the same number of rows
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5], [6]])

# Stack arrays horizontally (column-wise)
hstack_result = np.hstack((arr1, arr2))
print(hstack_result)

# 3. Example Comparing vstack() and hstack()
# Let’s combine two arrays both vertically and horizontally.

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

# Vertical stacking (row-wise)
vstack_result = np.vstack((arr1, arr2))
print("Vertical Stack:\n", vstack_result)

# Horizontal stacking (column-wise)
arr3 = np.array([[7], [8]])
hstack_result = np.hstack((arr1, arr3))
print("\nHorizontal Stack:\n", hstack_result)


[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]
Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]]

Horizontal Stack:
 [[1 2 7]
 [3 4 8]]


In [33]:
# 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
# array dimensions.

# In NumPy, fliplr() and flipud() are two methods used to flip arrays along different axes, specifically for 2D arrays or higher-dimensional arrays. Let’s explore how each function works and how it affects arrays.

import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Flip array horizontally (left-to-right)
fliplr_result = np.fliplr(arr)
print(fliplr_result)

# 2. np.flipud(): Flip Up to Down
# flipud() flips the array vertically, meaning it reverses the order of rows (top becomes bottom and vice versa). This function operates along the first axis (axis 0), which is typically the rows.

# Flip array vertically (up-to-down)
flipud_result = np.flipud(arr)
print(flipud_result)

# 3. Examples with 3D Arrays
# For higher-dimensional arrays, the functions work similarly, but the effect is limited to the last (for fliplr()) or first (for flipud()) axis.

arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Flip along last axis (horizontal)
fliplr_3d_result = np.fliplr(arr_3d)
print("fliplr on 3D array:\n", fliplr_3d_result)

# Flip along first axis (vertical)
flipud_3d_result = np.flipud(arr_3d)
print("\nflipud on 3D array:\n", flipud_3d_result)



[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
fliplr on 3D array:
 [[[ 4  5  6]
  [ 1  2  3]]

 [[10 11 12]
  [ 7  8  9]]]

flipud on 3D array:
 [[[ 7  8  9]
  [10 11 12]]

 [[ 1  2  3]
  [ 4  5  6]]]


In [39]:
# 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

# The array_split() function in NumPy is used to split an array into multiple sub-arrays. It is similar to the split() function but with a key difference: array_split() can handle uneven splits, meaning it doesn't require that the number of sections evenly divides the array.


#Syntax >> numpy.array_split(array, sections, axis=0)

import numpy as np

# Create an array of 7 elements
arr = np.arange(7)

# Split array into 3 parts
result = np.array_split(arr, 3)
print(result)




# Handling Uneven Splits:
# If the number of sections does not divide the array evenly, array_split() ensures that some sub-arrays will have one element more than others. It allocates the "extra" elements to the earlier sub-arrays in the list.

# Example: Uneven Split with array_split()

import numpy as np

# Create an array of 7 elements
arr = np.arange(7)

# Split array into 3 parts
result = np.array_split(arr, 3)
print(result)

# Comparison with np.split()
# If we used np.split() instead:

# np.split(arr, 3)

# Example: Uneven Split in 2D Arrays

arr_2d = np.arange(16).reshape(4, 4)


result_2d = np.array_split(arr_2d, 3, axis=0)
for part in result_2d:
    print(part)

#     Parameters and Variations:
# Number of Sections: You can pass either an integer to specify the number of equal parts, or a list of indices where the split should occur.

# Split array at specific indices
arr = np.arange(10)
result = np.array_split(arr, [3, 7])
print(result)



[array([0, 1, 2]), array([3, 4]), array([5, 6])]
[array([0, 1, 2]), array([3, 4]), array([5, 6])]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]


In [40]:
# 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
# operations?


# Vectorization and broadcasting are two key concepts in NumPy that significantly enhance the efficiency and performance of array operations. Let’s explore each concept in detail.

# 1. Vectorization
# Vectorization refers to the ability to perform operations on entire arrays (or large sections of arrays) rather than using explicit loops. This leverages optimized low-level implementations (typically in C or Fortran) for performance gains.


import numpy as np

# Create two large arrays
a = np.random.rand(1000000)
b = np.random.rand(1000000)

# Vectorized operation (element-wise addition)
c = a + b  # This is much faster than using a loop



# 2. Broadcasting
# Broadcasting is a powerful mechanism that allows NumPy to work with arrays of different shapes during arithmetic operations. It enables operations between arrays of different dimensions and sizes by "stretching" the smaller array across the larger one without making copies of the data.


# Broadcasting Rules:
# If the arrays have a different number of dimensions, the shape of the smaller-dimensional array is padded with ones on the left side until both shapes match.
# The size of each dimension is compared. They are compatible if:
# They are equal, or
# One of them is 1 (in which case, the smaller array is stretched).



# Create a 2D array
a = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 1D array
b = np.array([10, 20, 30])

# Broadcasting: b is stretched to match the shape of a
result = a + b
print(result)


[[11 22 33]
 [14 25 36]]
